//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export class DeleteStudyYearAdminRoleDto implements IDeleteStudyYearAdminRoleDto {
    studyYearId?: string;
    accountId?: string;

    constructor(data?: IDeleteStudyYearAdminRoleDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.studyYearId = _data["studyYearId"];
            this.accountId = _data["accountId"];
        }
    }

    static fromJS(data: any): DeleteStudyYearAdminRoleDto {
        data = typeof data === 'object' ? data : {};
        let result = new DeleteStudyYearAdminRoleDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["studyYearId"] = this.studyYearId;
        data["accountId"] = this.accountId;
        return data;
    }
}

export interface IDeleteStudyYearAdminRoleDto {
    studyYearId?: string;
    accountId?: string;
}

export class PostStudyYearAdminRoleDto implements IPostStudyYearAdminRoleDto {
    studyYearId?: string;
    accountId?: string;

    constructor(data?: IPostStudyYearAdminRoleDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.studyYearId = _data["studyYearId"];
            this.accountId = _data["accountId"];
        }
    }

    static fromJS(data: any): PostStudyYearAdminRoleDto {
        data = typeof data === 'object' ? data : {};
        let result = new PostStudyYearAdminRoleDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["studyYearId"] = this.studyYearId;
        data["accountId"] = this.accountId;
        return data;
    }
}

export interface IPostStudyYearAdminRoleDto {
    studyYearId?: string;
    accountId?: string;
}

export class WeLearnProblemDetails implements IWeLearnProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    constructor(data?: IWeLearnProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): WeLearnProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new WeLearnProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IWeLearnProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
}